# Production Stage
FROM nginx:alpine

# Copier la configuration Nginx
COPY nginx-frontend.conf /etc/nginx/conf.d/default.conf

# Copier les fichiers buildés (depuis le contexte local)
COPY dist /usr/share/nginx/html

# Exposer le port
EXPOSE 80

# Health check
HEALTHCHECK --interval=30s --timeout=10s --retries=3 \
    CMD wget --quiet --tries=1 --spider http://localhost:80 || exit 1

# Commande de démarrage
CMD ["nginx", "-g", "daemon off;"]
